// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFavorite(arg1) {
  return window['go']['services']['AppService']['AddFavorite'](arg1);
}

export function AddLog(arg1, arg2, arg3) {
  return window['go']['services']['AppService']['AddLog'](arg1, arg2, arg3);
}

export function ApplyUpdate(arg1) {
  return window['go']['services']['AppService']['ApplyUpdate'](arg1);
}

export function CancelDownload(arg1) {
  return window['go']['services']['AppService']['CancelDownload'](arg1);
}

export function CheckForUpdate() {
  return window['go']['services']['AppService']['CheckForUpdate']();
}

export function ClearAppCache() {
  return window['go']['services']['AppService']['ClearAppCache']();
}

export function ClearCompletedDownloads() {
  return window['go']['services']['AppService']['ClearCompletedDownloads']();
}

export function ClearDownloadHistory() {
  return window['go']['services']['AppService']['ClearDownloadHistory']();
}

export function ClearLogs() {
  return window['go']['services']['AppService']['ClearLogs']();
}

export function ClearSearchHistory() {
  return window['go']['services']['AppService']['ClearSearchHistory']();
}

export function DeleteFile(arg1) {
  return window['go']['services']['AppService']['DeleteFile'](arg1);
}

export function DeleteHistoryItem(arg1) {
  return window['go']['services']['AppService']['DeleteHistoryItem'](arg1);
}

export function DownloadFirmware(arg1, arg2) {
  return window['go']['services']['AppService']['DownloadFirmware'](arg1, arg2);
}

export function DummyProgress() {
  return window['go']['services']['AppService']['DummyProgress']();
}

export function ExportLogs(arg1) {
  return window['go']['services']['AppService']['ExportLogs'](arg1);
}

export function GetAccount() {
  return window['go']['services']['AppService']['GetAccount']();
}

export function GetActiveDownloads() {
  return window['go']['services']['AppService']['GetActiveDownloads']();
}

export function GetAllDownloads() {
  return window['go']['services']['AppService']['GetAllDownloads']();
}

export function GetAppDetails(arg1, arg2, arg3) {
  return window['go']['services']['AppService']['GetAppDetails'](arg1, arg2, arg3);
}

export function GetAppleDevices() {
  return window['go']['services']['AppService']['GetAppleDevices']();
}

export function GetAuthStatus() {
  return window['go']['services']['AppService']['GetAuthStatus']();
}

export function GetCacheSize() {
  return window['go']['services']['AppService']['GetCacheSize']();
}

export function GetConnectedDevices() {
  return window['go']['services']['AppService']['GetConnectedDevices']();
}

export function GetDeviceFirmwares(arg1) {
  return window['go']['services']['AppService']['GetDeviceFirmwares'](arg1);
}

export function GetDownloadHistory() {
  return window['go']['services']['AppService']['GetDownloadHistory']();
}

export function GetDownloadedIPAs(arg1) {
  return window['go']['services']['AppService']['GetDownloadedIPAs'](arg1);
}

export function GetFavorites() {
  return window['go']['services']['AppService']['GetFavorites']();
}

export function GetLogs(arg1) {
  return window['go']['services']['AppService']['GetLogs'](arg1);
}

export function GetSearchHistory(arg1) {
  return window['go']['services']['AppService']['GetSearchHistory'](arg1);
}

export function GetSettings() {
  return window['go']['services']['AppService']['GetSettings']();
}

export function InstallIPA(arg1, arg2) {
  return window['go']['services']['AppService']['InstallIPA'](arg1, arg2);
}

export function InstallMultipleIPAs(arg1, arg2) {
  return window['go']['services']['AppService']['InstallMultipleIPAs'](arg1, arg2);
}

export function IsDeviceConnected(arg1) {
  return window['go']['services']['AppService']['IsDeviceConnected'](arg1);
}

export function ListInstalledApps(arg1, arg2) {
  return window['go']['services']['AppService']['ListInstalledApps'](arg1, arg2);
}

export function Login(arg1, arg2, arg3, arg4) {
  return window['go']['services']['AppService']['Login'](arg1, arg2, arg3, arg4);
}

export function Logout() {
  return window['go']['services']['AppService']['Logout']();
}

export function LookupApp(arg1, arg2) {
  return window['go']['services']['AppService']['LookupApp'](arg1, arg2);
}

export function OpenFile(arg1) {
  return window['go']['services']['AppService']['OpenFile'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['services']['AppService']['OpenFolder'](arg1);
}

export function PairDevice(arg1) {
  return window['go']['services']['AppService']['PairDevice'](arg1);
}

export function PauseDownload(arg1) {
  return window['go']['services']['AppService']['PauseDownload'](arg1);
}

export function QueueDownload(arg1, arg2, arg3, arg4) {
  return window['go']['services']['AppService']['QueueDownload'](arg1, arg2, arg3, arg4);
}

export function RemoveFavorite(arg1) {
  return window['go']['services']['AppService']['RemoveFavorite'](arg1);
}

export function ResumeDownload(arg1) {
  return window['go']['services']['AppService']['ResumeDownload'](arg1);
}

export function RetryDownload(arg1) {
  return window['go']['services']['AppService']['RetryDownload'](arg1);
}

export function RevealInExplorer(arg1) {
  return window['go']['services']['AppService']['RevealInExplorer'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['services']['AppService']['SaveSettings'](arg1);
}

export function SearchApps(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['services']['AppService']['SearchApps'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SearchFavorites(arg1) {
  return window['go']['services']['AppService']['SearchFavorites'](arg1);
}

export function SelectDownloadDirectory(arg1) {
  return window['go']['services']['AppService']['SelectDownloadDirectory'](arg1);
}

export function SelectIPAFile() {
  return window['go']['services']['AppService']['SelectIPAFile']();
}

export function SelectMultipleIPAs() {
  return window['go']['services']['AppService']['SelectMultipleIPAs']();
}

export function SetContext(arg1) {
  return window['go']['services']['AppService']['SetContext'](arg1);
}

export function Shutdown() {
  return window['go']['services']['AppService']['Shutdown']();
}

export function ToggleFavorite(arg1) {
  return window['go']['services']['AppService']['ToggleFavorite'](arg1);
}

export function UninstallApp(arg1, arg2) {
  return window['go']['services']['AppService']['UninstallApp'](arg1, arg2);
}

export function ValidateIPA(arg1) {
  return window['go']['services']['AppService']['ValidateIPA'](arg1);
}
