// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function AddFavorite(arg1:models.FavoriteApp):Promise<void>;

export function AddLog(arg1:string,arg2:string,arg3:string):Promise<models.LogEntry>;

export function ApplyUpdate(arg1:string):Promise<void>;

export function CancelDownload(arg1:string):Promise<void>;

export function CheckForUpdate():Promise<models.UpdateInfo>;

export function ClearAppCache():Promise<void>;

export function ClearCompletedDownloads():Promise<void>;

export function ClearDownloadHistory():Promise<void>;

export function ClearLogs():Promise<void>;

export function ClearSearchHistory():Promise<void>;

export function DeleteHistoryItem(arg1:string):Promise<void>;

export function ExportLogs(arg1:string):Promise<string>;

export function GetAccount():Promise<models.AccountProfile>;

export function GetActiveDownloads():Promise<Array<models.DownloadTask>>;

export function GetAllDownloads():Promise<Array<models.DownloadTask>>;

export function GetAppDetails(arg1:number,arg2:string,arg3:string):Promise<models.AppDetailsOutput>;

export function GetAuthStatus():Promise<string>;

export function GetCacheSize():Promise<string>;

export function GetConnectedDevice():Promise<models.DeviceInfo>;

export function GetDownloadHistory():Promise<Array<models.DownloadTask>>;

export function GetFavorites():Promise<Array<models.FavoriteApp>>;

export function GetLogs(arg1:number):Promise<Array<models.LogEntry>>;

export function GetSearchHistory(arg1:number):Promise<Array<models.SearchHistoryItem>>;

export function GetSettings():Promise<models.AppSettings>;

export function InstallIPA(arg1:string):Promise<void>;

export function IsDeviceConnected():Promise<boolean>;

export function ListInstalledApps(arg1:string):Promise<Array<models.InstalledApp>>;

export function Login(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<models.AccountProfile>;

export function Logout():Promise<void>;

export function LookupApp(arg1:string,arg2:string):Promise<models.AppMetadata>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function PairDevice():Promise<void>;

export function PauseDownload(arg1:string):Promise<void>;

export function QueueDownload(arg1:models.AppMetadata,arg2:string,arg3:string,arg4:string):Promise<models.DownloadTask>;

export function RemoveFavorite(arg1:number):Promise<void>;

export function ResumeDownload(arg1:string):Promise<void>;

export function RetryDownload(arg1:string):Promise<void>;

export function RevealInExplorer(arg1:string):Promise<void>;

export function SaveSettings(arg1:models.AppSettings):Promise<void>;

export function SearchApps(arg1:string,arg2:string,arg3:number):Promise<Array<models.AppMetadata>>;

export function SearchFavorites(arg1:string):Promise<Array<models.FavoriteApp>>;

export function SelectDownloadDirectory(arg1:string):Promise<string>;

export function SelectIPAFile():Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;

export function Shutdown():Promise<void>;

export function ToggleFavorite(arg1:models.FavoriteApp):Promise<boolean>;

export function UninstallApp(arg1:string):Promise<void>;

export function ValidateIPA(arg1:string):Promise<models.IPAInfo>;
